---
title: "What is git?"
---

{{< video https://youtu.be/w3jLJU7DT5E >}}

Git(hub) has tow main purposes:

-   Version control: Track changes in your own files, code etc.
-   Collaboration: Contribute to someone else's files, code etc.
-   Efficient workflows
-   Massive resource of infomration, ideas, books, code, etc.
-   Publishing and hosting of code and material, websites etc.

# Git in a library context

## Scenario 1: Multiple librarians editing metadata for a collection

A librarian has exported a spreadsheet of metadata from a repository for cleaning and editing. She's working with a group of librarians and students, so they need to make sure edits don't conflict. They also need to be able to undo any edits and preserve the original metadata. Once edits are complete, the whole group wants to review the changes before re-ingesting the spreadsheet of metadata into the repository.

## Scenatio 2: Publishing a wesbite of the library

Librarians of a library decide that they want to create and publish a webiste for their library. They work on the code together and publish the webiste from github.

## Scenario 3: Publsihing a book together

Librarians of a libray want to publish a book on the proceedings of a community project. They decide to publish the book it as a web book out of Github and using Gitbook and will continue to add to the story as the library evolves.

## Challenge:

What will you use Github for?

